#!/bin/bash
cd ~/.config || exit
cp -r ~/Rice/Profiles ~/.config/rice_collection

if git status | grep -E "Bitwarden|YandexMusic|chromium|mozilla" >/dev/null; then
  echo "Error: Private data detected."
  exit 1
fi

if ping -c 1 github.com &>/dev/null; then
  echo "Syncing..."
  git add .
  if git diff-index --quiet HEAD --; then
    echo "Clean."
  else
    git commit -m "Update: $(date +'%H:%M:%S')"
    git push origin main
    echo "Done."
  fi
else
  echo "Error: Offline."
  exit 1
fi
